#
# GENERAL MODEL SETTINGS
#

# General parameters
startup_time: 12  # Length of startup period (during which some constraints are relaxed) [h]
# TODO change this to 'edge_period' and apply it similarly to end of optimized time series?

# Operation mode settings
opmode:
    horizon: 48  # Optimization period length [hours]
    window: 24  # Operation period length [hours]

#
# TECH DEFAULTS
#

techs:
    defaults:
        source_carrier:
        constraints:
            force_r: false
            r_eff: 1.0  # Resource <> storage conversion efficiency [dimensionless]
            r_area_max: false  # Installed collector area [m2], set this to `false` to force to 1.0
            r_cap_max: inf  # Maximum installed resource <> storage conversion capacity [kW]
            r_scale: 1.0  # Scale resource by this value, default should always be 1.0 [dimensionless]
            r_scale_to_peak: false  # Scale resource such that its peak is as defined here, `false` to disable
                                    # NB: this only works if r is read as a time series from CSV, otherwise simply set
                                    # r statically to the desired value!
            allow_rsec: false  # Allow secondary resource during startup_time?
            s_init: 0  # Initial storage level [kWht]
            s_cap_max: 0  # Maximum storage size [kWht]
            s_loss: 0  # Storage heat loss rate [per hour]
            e_eff: 1.0
            e_eff_ref: false  # Currently only used to calculate storage size based on a given storage time. If set to false, e_eff is used for that instead.
            e_cap_max: 0  # Maximum turbine size [kWe]
            e_can_be_negative: false
            e_ramping:  false # Ramping rate [fraction of installed capacity per hour], set to false to disable
        costs:  # All costs should be set to 0 by default
            default:  # The default is looked up for any value not defined for a specific cost class
                s_cap: 0  # Cost of storage [USD/kWht]
                r_area: 0  # Cost of collector field [USD/m2]
                r_cap: 0  # Cost of tower and receiver [EUR/kWt]
                e_cap: 0  # Cost of power block [USD/kWe]
                om_frac: 0  # Yearly O&M costs [fraction of total investment]
                om_var: 0  # Variable O&M costs [USD/kWhe]
                om_fuel: 0  # Fuel costs [USD/kWht]
        depreciation:  # Capital depreciation settings
            plant_life: 25  # Lifetime of a plant [years]
            interest:
                default: 0  # If interest not set for a class it is zero
                monetary: 0.10  # Interest rate [dimensionless]
        weight: 1  # Cost weight in objective function (higher: relatively more expensive)
    supply:
        parent: defaults
    demand:
        parent: defaults
        constraints:
            r: 0
            force_r: true
            e_cap_max: inf
            e_can_be_negative: true
    unmet_demand:
        parent: defaults
        constraints:
            r: inf
            e_cap_max: inf
        costs:
            monetary:
                om_fuel: 1.0e+9
    storage:
        parent: defaults
        constraints:
            r: 0  # Not used but still must be defined
            e_can_be_negative: true
    transmission:
        parent: defaults
        constraints:
            r: 0  # Not used but still must be defined
            e_cap_max: inf
            e_can_be_negative: true
    conversion:
        parent: defaults
        constraints:
            r: 0  # Not used but still must be defined
            e_can_be_negative: true
