#
# NB Parts of this file are automatically parsed and extracted for the configuration reference documentation.
# See `doc/user/configuration_reference.rst` and `doc/generate_tables.py`, which populates
# the `doc/user/includes` directory
#

#
# GENERAL MODEL SETTINGS
#

# General parameters
startup_time: 12  # Length of startup period (hours)

# Operation mode settings
opmode:
    horizon: 48  # Optimization period length (hours)
    window: 24  # Operation period length (hours)

# Per-carrier system margins
system_margin:
    power: 0

availability: false  # Disable availability constraint by default

#
# TECH DEFAULTS
#

techs:
    defaults:
        stack_weight: 100
        color: false  # If no color is defined, a random one will be chosen
        source_carrier: false # Defaults to false, allows technologies to define a carrier to consume
        group: false
        constraints:
            force_r: false
            r_unit: power  # Power or energy.
            r_eff: 1.0  # Resource <> storage conversion efficiency [dimensionless]
            r_area_max: false  # Installed collector area [m2], set this to `false` to force to 1.0
            r_area_per_e_cap: false  # If set, forces r_area to follow e_cap with the given ratio
            r_cap_max: inf  # Maximum installed resource <> storage conversion capacity [kW]
            r_scale: 1.0  # Scale resource by this value, default should always be 1.0 [dimensionless]
            r_scale_to_peak: false  # Scale resource such that its peak is as defined here, `false` to disable. Only works if r: file.
            allow_rb: false  # Allow secondary resource
            rb_startup_only: false  # Secondary resource during startup_time only
            rb_eff: 1.0  # Secondary resource <> storage conversion efficiency [dimensionless]
            rb_cap_max: inf  # Maximum installed secondary resource <> storage conversion capacity [kW]
            rb_cap_max_force: false  # If true, force rb_cap to equal rb_cap_max or the chosen rb_cap_follows value
            rb_cap_follows:  false  # Can be set to 'e_cap' or 'r_cap' to force rb_cap_max to the respective value and ignore the rb_cap_max given here, else must be false
            s_init: 0  # Initial storage level [kWh]
            s_cap_max: 0  # Maximum storage size [kWh]
            s_cap_max_force: false  # If true, force s_cap to equal s_cap_max
            use_s_time: false  # Use full load hours for storage sizing?
            s_time_max: 0  # Max storage time [full load hours]
            s_loss: 0  # Storage loss rate [per hour]
            cf_max: false  # Maximum capacity factor, set to false to disable
            e_prod: true  # TODO
            e_con: false  # TODO
            c_eff: 1.0  # Carrier efficiency (additional losses as energy gets transferred to carrier, e.g. due to plant parasitic consumption)
            e_eff: 1.0  # TODO
            e_eff_ref: false  # Reference efficiency. If set to false, e_eff is used instead.
            e_cap_max: 0  # Maximum e_cap [kW]
            e_cap_max_force: false  # If true, force e_cap to equal e_cap_max
            e_cap_max_scale: 1.0  # Scale e_cap_max by this value, default is 1.0
            e_cap_min_use: false  # Set to a value between 0 and 1 to force minimum capacity use for production technologies
            e_ramping:  false  # Ramping rate [fraction of installed capacity per hour], set to false to disable
            availability: 1.0  # UNDOCUMENTED
        costs:
            default:  # These default are looked up for any value not defined for a specific cost class
                s_cap: 0  # Cost of storage capacity (per kWh)
                r_area: 0  # Cost of resource collector area (per m2)
                r_cap: 0  # Cost of resource conversion capacity (per kW]
                rb_cap: 0  # Cost of secondary resource conversion capacity (per kW)
                e_cap: 0  # Cost of carrier conversion capacity (per kW gross)
                om_frac: 0  # Yearly O&M costs (fraction of total investment)
                om_fixed: 0  # Yearly O&M costs (per kW of e_cap)
                om_var: 0  # Variable O&M costs (per kWh of es_prod)
                om_fuel: 0  # Fuel costs (per kWh of r used)
                om_rb: 0  # Fuel costs for secondary resource (per kWh of rb used)
        depreciation:
            plant_life: 25  # Lifetime of a plant (years)
            interest:
                default: 0  # Default interest rate if not specified for a cost class ``k``
                monetary: 0.10  # Interest rate for the ``monetary`` cost class
        weight: 1.0  # Cost weight in objective function (higher: relatively more expensive)
    supply:
        parent: defaults
    demand:
        parent: defaults
        constraints:
            r: 0
            force_r: true
            e_cap_max: inf
            e_prod: false
            e_con: true
    unmet_demand:  # Unmet demand that is not child of 'supply' so doesn't get grouped with it
        stack_weight: 0
        color: '#666666'
        parent: defaults
        constraints:
            r: inf
            e_cap_max: inf
        costs:
            monetary:
                om_var: 1.0e+9
    unmet_demand_as_supply_tech:  # Unmet demand that IS a child of 'supply' so gets treated like a regular supply technology for grouping purposes
        stack_weight: 0
        color: '#666666'
        parent: supply
        constraints:
            r: inf
            e_cap_max: inf
        costs:
            monetary:
                om_var: 1.0e+9
    storage:
        parent: defaults
        constraints:
            r: 0  # Not used but still must be defined as 0
            e_con: true
    transmission:
        parent: defaults
        constraints:
            r: inf  # Not used but still must be defined as inf
            e_cap_max: inf
            e_con: true
    conversion:
        parent: defaults
        constraints:
            r: inf  # Not used but still must be defined as inf
            e_con: true
