#
# GENERAL MODEL SETTINGS
#

# General parameters
startup_time: 12  # Length of startup period (during which some constraints are relaxed) [h]
# TODO change this to 'edge_period' and apply it similarly to end of optimized time series?

# Operation mode settings
opmode:
    horizon: 48  # Optimization period length [hours]
    window: 24  # Operation period length [hours]

#
# MODEL-WIDE DEFAULTS
#

system_margin:
    power: 0

#
# TECH DEFAULTS
#

techs:
    defaults:
        source_carrier: false # Defaults to false, allows technologies to define a carrier to consume
        constraints:
            force_r: false
            r_eff: 1.0  # Resource <> storage conversion efficiency [dimensionless]
            r_area_max: false  # Installed collector area [m2], set this to `false` to force to 1.0
            r_area_per_e_cap: false  # If set, forces r_area to follow e_cap with the given ratio
            r_cap_max: inf  # Maximum installed resource <> storage conversion capacity [kW]
            r_scale: 1.0  # Scale resource by this value, default should always be 1.0 [dimensionless]
            r_scale_to_peak: false  # Scale resource such that its peak is as defined here, `false` to disable
                                    # NB: this only works if r is read as a time series from CSV, otherwise simply set
                                    # r statically to the desired value!
            allow_rs_: false  # Allow secondary resource during startup_time?
            s_init: 0  # Initial storage level [kWh]
            s_cap_max: 0  # Maximum storage size [kWh]
            s_cap_max_force: false  # If true, force s_cap to equal s_cap_max
            use_s_time: False  # Use full load hours for storage sizing?
            s_time_max: 0  # Max storage time [full load hours]
            s_loss: 0  # Storage loss rate [per hour]
            cf_max: false  # Maximum capacity factor, set to false to disable
            e_can_be_negative: false
            e_eff: 1.0
            e_eff_ref: false  # Reference efficiency. If set to false, e_eff is used instead.
            e_cap_max: 0  # Maximum e_cap [kW]
            e_cap_max_force: false  # If true, force e_cap to equal e_cap_max
            e_cap_max_scale: 1.0  # Scale e_cap_max by this value, default is 1.0
            e_cap_min_use: false  # Set to a value between 0 and 1 to force minimum capacity use for production technologies
            e_ramping:  false  # Ramping rate [fraction of installed capacity per hour], set to false to disable
        costs:  # All costs should be set to 0 by default
            default:  # The default is looked up for any value not defined for a specific cost class
                s_cap: 0  # Cost of storage [cost/kWh]
                r_area: 0  # Cost of collector area [cost/m2]
                r_cap: 0  # Cost of resource conversion capacity [cost/kW]
                e_cap: 0  # Cost of carrier conversion capacity [USD/kWe]
                om_frac: 0  # Yearly O&M costs [fraction of total investment]
                om_fixed: 0  # Yearly O&M costs [cost/kW installed capacity]
                om_var: 0  # Variable O&M costs [cost/kWh]
                om_fuel: 0  # Fuel costs [cost/kWh]
        depreciation:  # Capital depreciation settings
            plant_life: 25  # Lifetime of a plant [years]
            interest:
                default: 0  # If interest not set for a class it is zero
                monetary: 0.10  # Interest rate [dimensionless]
        weight: 1  # Cost weight in objective function (higher: relatively more expensive)
    supply:
        parent: defaults
    demand:
        parent: defaults
        constraints:
            r: 0
            force_r: true
            e_cap_max: inf
            e_can_be_negative: true
    unmet_demand:
        parent: defaults
        constraints:
            r: inf
            e_cap_max: inf
        costs:
            monetary:
                om_var: 1.0e+9
    storage:
        parent: defaults
        constraints:
            r: 0  # Not used but still must be defined as 0
            e_can_be_negative: true
    transmission:
        parent: defaults
        constraints:
            r: inf  # Not used but still must be defined as inf
            e_cap_max: inf
            e_can_be_negative: true
    conversion:
        parent: defaults
        constraints:
            r: inf  # Not used but still must be defined as inf
            e_can_be_negative: true
