#
# NB Parts of this file are automatically parsed and extracted for the configuration reference documentation.
# See `doc/user/configuration_reference.rst` and `doc/generate_tables.py`, which populates
# the `doc/user/includes` directory
#

##
# Model-wide default settings
##

model:
    name: null

    mode: plan  # Choices: plan, operate

    data_path:  null  # Path to time series data

    startup_time: 12  # Length of startup period (hours)

    opmode:  # Operation mode settings
        horizon: 48  # Optimization period length (hours)
        window: 24  # Operation period length (hours)

    system_margin:  # Per-carrier system margins
        power: 0

    subset_tech: []  # Subset of technologies
    subset_loc: []  # Subset of locations
    subset_time: []  # Subset of timesteps as a list with two elements setting from and to, e.g. ['2005-01-01', '2005-01-05']



##
# Base technology groups
##

tech_groups:
    supply:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]  # FIXME for all tech_groups
        allowed_constraints: ['resource', 'resource_unit', 'energy_prod', 'energy_eff']  # FIXME for all tech_groups
        allowed_costs: []  # FIXME for all tech_groups
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            resource: inf
            resource_unit: power
            energy_prod: true
    supply_plus:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: []
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            resource: inf
            resource_unit: power
            resource_eff: 1.0
            energy_prod: true
    demand:
        required_constraints: ['resource', ['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: []
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            resource_unit: power
            force_resource: true
            energy_con: true
    unmet_demand:
        required_constraints: []
        allowed_constraints: []
        essentials:
            parent: null
            stack_weight: 0
            color: '#666666'
        constraints:
            resource: inf
            resource_unit: power
            energy_cap_max: inf
            energy_prod: true
        costs:
            monetary:
                om_var: 1.0e+9
    storage:
        required_constraints: [['energy_cap_max', 'energy_cap_equals', 'storage_cap_max', 'storage_cap_equals'], 'charge_rate']
        allowed_constraints:
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
            storagenergy_cap_max: inf
    transmission:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: []
        essentials:
                parent: null
                stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
    conversion:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: []
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
    conversion_plus:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: []
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
