##
# IMPORT OTHER FILES
##

# Can either be a relative path, absolute path, or one that starts with {{ module }} to access the module directory

import:
    - 'techs.yaml'
    - 'locations.yaml'

##
# OBJECTIVE FUNCTION
##

objective: constraints.objective.objective_cost_minimization

##
# ADDITIONAL CONSTRAINTS
##

# Python statements to evaluate before loading additional_constraints
# Can be used to import additional constraint modules
constraints_pre_load:

# List of additional constraints to load
constraints:
    - constraints.ramping.ramping_rate

# Other model-wide settings
system_margin:
    power: 0
    heat: 0