#
# NB Parts of this file are automatically parsed and extracted for the configuration reference documentation.
# See `doc/user/configuration_reference.rst` and `doc/generate_tables.py`, which populates
# the `doc/user/includes` directory
#

##
# Model-wide default settings
##

run:
    backend: pyomo
    solver: glpk
    solver_options: null  # FIXME document
    solver_io: null  # FIXME check what options exist here (lp, file?)
    save_logs: null  # Directory into which to save logs and temporary files. Also turns on symbolic solver labels in the Pyomo backend
    save_netcdf: null  # Path to which to save a single NetCDF results file
    save_csv: null  # Directory into which to save a set of CSV results files
    random_seed: null  # Seed for random number generator used during clustering

model:
    name: null
    mode: plan  # Choices: plan, operation
    timeseries_data_path: null  # Path to time series data
    timeseries_dateformat: '%Y-%m-%d %H:%M:%S'  # Timestamp format of all time series data when read from file
    timeseries_data: null  # Dict of dataframes with time series data (when passing in dicts rather than YAML files to Model constructor)
    subset_time: []  # Subset of timesteps as a two-element list giving the range, e.g. ['2005-01-01', '2005-01-05'], or a single string, e.g. '2005-01'
    objective: 'cost_minimization'
    system_margin:  # Per-carrier system margins
        power: 0

##
# Base technology groups
##

tech_groups:
    supply:
        required_constraints: ['resource', ['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: ['energy_prod', 'lifetime', 'resource', 'force_resource', 'resource_unit', 'resource_eff', 'resource_area_min', 'resource_area_max', 'resource_area_equals', 'resource_area_per_energy_cap', 'resource_cap_min', 'resource_cap_max', 'resource_cap_equals', 'resource_cap_equals_energy_cap', 'resource_scale', 'resource_scale_to_peak', 'energy_eff', 'energy_cap_min', 'energy_cap_max', 'energy_cap_equals', 'energy_cap_total_max', 'energy_cap_total_equals', 'energy_cap_scale', 'energy_cap_min_use', 'energy_cap_per_unit', 'energy_ramping', 'energy_eff_per_distance', 'export_cap', 'export_carrier', 'units_min', 'units_max', 'units_equals']
        allowed_costs: ['interest_rate', 'resource_area', 'resource_cap', 'energy_cap', 'om_annual_investment_fraction', 'om_annual', 'om_prod', 'om_con', 'export', 'purchase', 'depreciation_rate']
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            resource: inf
            resource_unit: power
            energy_prod: true
    supply_plus:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: ['energy_prod', 'lifetime', 'resource', 'force_resource', 'resource_unit', 'resource_eff', 'resource_area_min', 'resource_area_max', 'resource_area_equals', 'resource_area_per_energy_cap', 'resource_cap_min', 'resource_cap_max', 'resource_cap_equals', 'resource_cap_equals_energy_cap', 'resource_scale', 'resource_scale_to_peak', 'parasitic_eff', 'energy_eff', 'energy_cap_min', 'energy_cap_max', 'energy_cap_equals', 'energy_cap_total_max', 'energy_cap_total_equals', 'energy_cap_scale', 'energy_cap_min_use', 'energy_cap_per_unit', 'energy_ramping', 'energy_eff_per_distance', 'export_cap', 'export_carrier', 'units_min', 'units_max', 'units_equals', 'storage_initial', 'storage_cap_min', 'storage_cap_max', 'storage_cap_equals', 'storage_cap_per_unit', 'charge_rate', 'storage_time_max', 'storage_loss']
        allowed_costs: ['interest_rate', 'storage_cap', 'resource_area', 'resource_cap', 'energy_cap', 'energy_cap_per_distance', 'om_annual_investment_fraction', 'om_annual', 'om_prod', 'om_con', 'export', 'purchase', 'depreciation_rate']
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            resource: inf
            resource_unit: power
            resource_eff: 1.0
            energy_prod: true
    demand:
        required_constraints: ['resource']
        allowed_constraints: ['energy_con', 'resource', 'force_resource', 'resource_unit', 'resource_scale', 'resource_scale_to_peak']
        allowed_costs: []
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            resource_unit: power
            force_resource: true
            energy_con: true
    unmet_demand:
        required_constraints: []
        allowed_constraints: ['energy_prod', 'energy_cap_max', 'energy_prod', 'resource', 'resource_unit']
        allowed_costs: ['om_prod']
        essentials:
            parent: null
            stack_weight: 0
            color: '#666666'
        constraints:
            resource: inf
            resource_unit: power
            energy_cap_max: inf
            energy_prod: true
        costs:
            monetary:
                om_prod: 1.0e+9
    storage:
        required_constraints: [['energy_cap_max', 'energy_cap_equals', 'storage_cap_max', 'storage_cap_equals'], 'charge_rate']
        allowed_constraints: ['energy_prod', 'energy_con', 'lifetime', 'resource_cap_max', 'resource_cap_equals', 'resource_cap_equals_energy_cap', 'resource_scale', 'resource_scale_to_peak', 'energy_eff', 'energy_cap_min', 'energy_cap_max', 'energy_cap_equals', 'energy_cap_total_max', 'energy_cap_total_equals', 'energy_cap_scale', 'energy_cap_min_use', 'energy_cap_per_unit', 'energy_ramping', 'storage_initial', 'storage_cap_min', 'storage_cap_max', 'storage_cap_equals', 'storage_cap_per_unit', 'charge_rate', 'storage_time_max', 'storage_loss', 'units_min', 'units_max', 'units_equals']
        allowed_costs: ['interest_rate', 'storage_cap', 'energy_cap', 'om_annual_investment_fraction', 'om_annual', 'om_prod', 'purchase', 'depreciation_rate']
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
            storage_cap_max: inf
    transmission:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: ['energy_prod', 'energy_con', 'lifetime', 'energy_con', 'energy_prod', 'energy_eff_per_distance', 'energy_eff']
        allowed_costs: ['interest_rate', 'energy_cap', 'energy_cap_per_distance', 'om_annual_investment_fraction', 'om_annual', 'om_prod', 'purchase', 'depreciation_rate']
        essentials:
                parent: null
                stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
    conversion:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: ['energy_prod', 'energy_con', 'lifetime', 'energy_eff', 'energy_cap_min', 'energy_cap_max', 'energy_cap_equals', 'energy_cap_total_max', 'energy_cap_total_equals', 'energy_cap_scale', 'energy_cap_min_use', 'energy_cap_per_unit', 'energy_ramping', 'energy_eff_per_distance', 'export_cap', 'export_carrier', 'units_min', 'units_max', 'units_equals']
        allowed_costs: ['interest_rate', 'energy_cap', 'om_annual_investment_fraction', 'om_annual', 'om_prod', 'purchase', 'depreciation_rate']
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
    conversion_plus:
        required_constraints: [['energy_cap_max', 'energy_cap_equals']]
        allowed_constraints: ['energy_prod', 'energy_con', 'lifetime', 'carrier_ratios', 'resource', 'force_resource', 'resource_unit', 'resource_eff', 'resource_area_min', 'resource_area_max', 'resource_area_equals', 'resource_area_per_energy_cap', 'resource_cap_min', 'resource_cap_max', 'resource_cap_equals', 'resource_cap_equals_energy_cap', 'resource_scale', 'resource_scale_to_peak', 'energy_eff', 'energy_cap_min', 'energy_cap_max', 'energy_cap_equals', 'energy_cap_total_max', 'energy_cap_total_equals', 'energy_cap_scale', 'energy_cap_min_use', 'energy_cap_per_unit', 'energy_ramping', 'energy_eff_per_distance', 'export_cap', 'export_carrier', 'storage_initial', 'storage_cap_min', 'storage_cap_max', 'storage_cap_equals', 'storage_cap_per_unit', 'charge_rate', 'storage_time_max', 'storage_loss', 'units_min', 'units_max', 'units_equals']
        allowed_costs: ['interest_rate', 'storage_cap', 'resource_area', 'resource_cap', 'energy_cap', 'om_annual_investment_fraction', 'om_annual', 'om_prod', 'om_con', 'export', 'purchase', 'depreciation_rate']
        essentials:
            parent: null
            stack_weight: 0
        constraints:
            energy_prod: true
            energy_con: true
