#
# NODES
#

# ONLY the following constraints can be overriden on a per-node and per-tech basis (for now). Attempting to override any others will cause errors or simply be ignored:
# * x_map
# * constraints: r, r_eff, e_eff, r_scale_to_peak, s_cap_max, s_init, r_cap_max, r_area_max, e_cap_max

# x_map allows defining which columns in the underlying data file are to be mapped to the node indices defined here.

nodes:
    r1:
        level: 1
        within:
        techs: ['demand', 'unmet_demand', 'ccgt']
        override:
            demand:
                x_map: 'a: r1'
                constraints:
                    r: file=demand-r1_r.csv
                    r_scale_to_peak: -60000
            ccgt:
                constraints:
                    e_cap_max: 20000
    r2:
        level: 1
        within:
        techs: ['demand', 'unmet_demand']
        override:
            demand:
                x_map: 'a: r2'
                constraints:
                    r: file=demand-r2_r.csv
                    r_scale_to_peak: -5000

    33,34,75:
        level: 0
        within: r1
        techs: ['csp']
        override:
            csp:
                constraints:
                    r: file

#
# TRANSMISSION CAPACITIES
#
links:
    r1,r2:
        hvac:
            constraints:
                e_cap_max: 10000
