#
# NODES
#

nodes:
    r1:
        level: 1
        within:
        techs: ['demand', 'unmet_demand', 'ccgt']
        override:
            demand:
                x_map: 'a: r1'
                constraints:
                    r: file=demand-r1_r.csv
                    r_scale_to_peak: -50000
            ccgt:
                constraints:
                    e_cap_max: 40000
    r2:
        level: 1
        within:
        techs: ['demand', 'unmet_demand']
        override:
            demand:
                x_map: 'a: r2'
                constraints:
                    r: file=demand-r2_r.csv
                    r_scale_to_peak: -5000

    tamanrasset,cardak,toledo:
        level: 0
        within: r1
        techs: ['csp']
        override:
            csp:
                constraints:
                    r: file
                    r_eff: file
                    e_eff: file

#
# TRANSMISSION CAPACITIES
#

links:
    r1,r2:
        hvac:
            constraints:
                e_cap_max: 10000
