name:  # Run name -- distinct from model name!

model:  # Model configuration file

output:  # Only used if run via the 'calliope run' command-line tool
    format: csv  # Choices: netcdf, csv
    path: 'Output'  # Will be created if it doesn't exist

solver: glpk  # Tested choices: glpk, cplex, gurobi

solver_io:  # FIXME check what options exist here (lp, file?)

##
# TIME RESOLUTION ADJUSTMENT
##

time:
    function:  # Name of function to use to reduce time dimension
    function_options:  # Dict of function arguments

##
# MODEL SETTINGS OVERRIDE
##

# Override anything in the model configuration

override:

##
# DEBUG OPTIONS
##

debug:
    keep_temp_files: false  # Keep temporary files
    symbolic_solver_labels: false  # Use human-readable component labels? (slower)
    echo_solver_log: true  #
