#
# RUN SETTINGS
#

input:
    model: '{{ module }}/config/model.yaml'
    data_path:  '{{ module }}/example'

output:
    save: false
    path: 'Output'

mode: plan  # Choices: plan, operate

# NB: Parallel settings are ignored except if the model is run in parallel mode.
# If mode is parallel, output.save is always set to true and output.path is
# overridden by the run name

parallel:  # Options apply if mode is parallel
    name: example-model  # Name of this run
    environment: bsub  # Choices: bsub, qsub
    style: single  # Choices: single, array
    additional_lines:  # Additional lines to add in run script before calling model, e.g. virtualenv setup
    iterations:  # Give iterations  as `parameter: [values]` entries
        override.locations.r1.techs: [['demand', 'unmet_demand', 'ccgt'],
                                  ['demand', 'unmet_demand',]]
        subset_t: [['2005-01-01', '2005-01-31'],
                   ['2005-02-01', '2005-02-31']]
    resources:  # Currently only compatible with `bsub` environment
        threads:  # Set to request a non-default number of threads
        wall_time:   # Set to request a non-default run time in minutes
        memory:  # Set to request a non-default amount of memory in MB

#
# SUBSETS
#
# Leave any of these empty to disable subsetting

subset_y: []
subset_x: []
subset_t: ['2005-01-01', '2005-01-31']

#
# MODEL SETTINGS OVERRIDE
#

override:

#
# SOLVER AND DEBUG OPTIONS
#

solver: cplex

# solver_options:
    # emphasis.memory: 1  # Set to 1 to conserve memory where possible
    # workmem: 1000  # Allow CPLEX use to 1000 MB of memory, default: 128
    # threads: 1
    # lpmethod: 4  # Use barrier method

debug:
    keepfiles: false
    symbolic_solver_labels: false
