#
# TECHNOLOGY DEFINITIONS
#

techs:
    ccgt:
        parent: supply
        carrier: power
        constraints:
            r: inf
            e_cap_max: 40000  # Maximum installed generation capacity [kWe]
        costs:
            monetary:
                e_cap: 750
                om_fuel: 0.12
            emissions:
                om_fuel: 0.25  # Assuming new build LNG, http://www.zerocarbonhub.org/resourcefiles/Carbon_Emission_Factors_for_Fuels-methodology_and_values_for_2013_and_2016.pdf
    csp:
        parent: supply
        carrier: power
        constraints:
            # -- Begin CSP-specific constraints --
            use_s_time: true  # Use s_time to calculate s_cap_max?
            s_time: 15   # Maximum storage time [h]
            # -- End CSP-specific constraints --
            r: 0
            r_eff: 1.0
            r_eff_ref: 1.0
            e_eff: 0.4
            e_eff_ref: 0.4
            r_area_max: 318000  # Maximum solar field size [m2]
            s_cap_max: 745321  # Overriden by s_time if use_s_time = 1
            s_loss: 0.002
            e_cap_max: 20000  # Maximum turbine size [kWe]
        costs:
            monetary:
                s_cap: 30
                r_area: 200
                r_cap: 200
                e_cap: 1350
                om_var: 0.002
        depreciation:
            monetary:
                interest: 0.15
    heater:
        parent: conversion
        carrier: heat
        source_carrier: power
        constraints:
            e_eff: 0.8
            e_cap_max: 1000
        costs:
            monetary:
                e_cap: 200

#
# Demands
#

    demand_power:
        parent: demand
        carrier: power
    unmet_demand_power:
        parent: unmet_demand
        carrier: power
    demand_heat:
        parent: demand
        carrier: heat
    unmet_demand_heat:
        parent: unmet_demand
        carrier: heat

#
# Transmission
#

    hvac:
        parent: transmission
        carrier: power
        constraints:
            e_eff: 0.85
        costs:
            monetary:
                e_cap: 200
    hvdc:
        parent: transmission
        carrier: power
        constraints:
            e_eff: 0.95
        costs:
            monetary:
                e_cap: 200
