# Modified from example at http://conda.pydata.org/docs/travis.html

language: python
sudo: false  # Use container-based infrastructure

matrix:
  include:
    - env:
      - JOB_TYPE="test"

before_install:
  - "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;"
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda env create -n calliope --file requirements/base.yml
  - source activate calliope
  - conda env update --file requirements/travis.yml
  - pip install --no-cache-dir .

script: "make ci"

after_success:
  - if [ "${JOB_TYPE}" = "test" ]; then coveralls; fi
