sudo: false  # Use container-based infrastructure
addons:
  apt_packages:
    - glpk-utils
    - libhdf5-serial-dev  # Required for pip to compile pytables
language: python
python:
  - "3.4"
env:
  - PIP_DOWNLOAD_CACHE=$HOME/.cache/pip  # Ensure pip-accel uses right dir
install:
  - "pip install --no-cache-dir pip-accel"  # Use pip-accel to cache binaries
  - "pip-accel install -r requirements.txt"
  - 'pip-accel install cython --install-option="--no-cython-compile"'
  - "pip-accel install tables==3.1.0"  # Fails if in requirements.txt
  - "pip install --no-cache-dir ."
cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip
script: "py.test --cov calliope --cov-report term-missing"
after_success: coveralls
