name: calliope

channels:
    - conda-forge
    - anaconda

dependencies:
    - python=3.6
    - bottleneck
    - click
    - glpk=4.61
    - hdf5
    - libnetcdf
    - netcdf4
    - numexpr
    - numpy=1.12.1
    - pandas=0.21
    - plotly
    - pyomo=5.2
    - pytest
    - pytest-cov
    - ruamel.yaml<=0.15
    - scikit-learn
    - scipy
    - xarray=0.10
