name: calliope

channels:
    - anaconda
    - cachemeorg  # for glpk=4.57 on linux64, osx64, win64
    - conda-forge

dependencies:
    - python=3.5
    - basemap
    - bottleneck
    - click
    - geos
    - glpk=4.57  # 4.60 causes problems with current version of Pyomo
    - hdf5
    - libnetcdf
    - matplotlib=1.5.1
    - netcdf4
    - networkx
    - numexpr
    - numpy=1.11
    - pandas=0.18.0
    - pyomo=4.3.11377
    - pytest
    - pytest-cov
    - python-coveralls
    - pyyaml
    - scipy
    - xarray=0.7.2
