name: calliope

channels:
 - conda-forge

dependencies:
- python=3.5
- basemap
- click
- geos
- glpk=4.59
- hdf5
- libnetcdf
- matplotlib=1.5.1
- netcdf4
- networkx
- numexpr
- numpy=1.11
- pandas=0.18.0
- pyomo=4.3.11377
- pytest
- pytest-cov
- python-coveralls
- pyyaml
- xarray=0.7.2
