#
# RUN SETTINGS
#

input:
    path:  'Input/NA-6hr-full'
    demand: 'DemandTable_EU.csv'
    D_max: 800000  # Set to: P_max * len(subset_i) * 0.8

output:
    save: false
    path: 'Output'

subset_i: [33, 75, 34, 23, 85, 86, 16, 98, 57, 36]  # Leave empty to disable subsetting
subset_t: ['2005-01-01', '2005-12-31']

#
# MODEL SETTINGS OVERRIDE
#

override:
    P_max: 100000
    sf_max: 7950000
    E_time: 30
    scale_sf: 32
