#
# GENERAL MODEL SETTINGS
#

# General parameters
startup_time: 12  # Length of startup period (during which some constraints are relaxed) [h]
# TODO change this to 'edge_period' and apply it similarly to end of optimized time series?

# Operation mode settings
opmode:
    horizon: 48  # Optimization period length [hours]
    window: 24  # Operation period length [hours]

#
# TECHNOLOGIES
#

# Allowed technologies
techs: ['csp']
#techs: ['csp', 'ccgt', 'demand_power']

# Objective function weights
tech_weights:
    default: 1
    ccgt: 10

slack_weight: 1.0e+9

# Technology constraints
constraints:
    default:
        r_eff: 1.0  # Storage throughput efficiency [dimensionless]
        r_cap_max: 1.0e+9
        s_init: 0  # Initial storage contents [kWht]
        s_cap_max: 0  # Maximum storage size [kWht]
        s_loss: 0  # Storage heat loss rate [per hour]
        e_cap_max: 0  # Maximum turbine size [kWe]
    ccgt:
        e_cap_max: 100000  # Maximum turbine size [kWe]
    csp:
        # -- Begin CSP-specific constraints --
        use_s_time: true  # Use s_time to calculate s_cap_max?
        s_time: 15  # Maximum storage time [h]
        # -- End CSP-specific constraints --
        r_area_max: 318000  # Maximum solar field size [m2], overridden if scale_sf is True
        s_cap_max: 745321  # overriden by s_time if use_s_time = 1
        s_loss: 0.002  # Storage heat loss rate [per hour]
        e_cap_max: 20000  # Maximum turbine size [kWe]
    demand_power:
        e_cap_max: infinity  # TODO TODO TODO

# Technology costs
costs:
    default:
        s_cap : 0  # Cost of storage [USD/kWht]
        r_area : 0  # Cost of collector field [USD/m2]
        r_cap: 0  # Cost of tower and receiver [EUR/kWt]
        e_cap: 0  # Cost of power block [USD/kWe]
        om_frac: 0  # Yearly O&M costs [fraction of total investment]
        om_var:: 0  # Variable O&M costs [USD/kWhe]
        om_fuel: 0  # Fuel costs [USD/kWht]
    ccgt:
        e: 750
        om_fuel: 0.12
    csp:
        s_cap: 30
        r_area: 200
        r_cap: 200
        e_cap: 1350
        om_var: 0.002
        # -- Begin CSP-specific costs --
        rec_per_sf: 0.54  # kWt of receiver needed per m2 of solar field
        # -- End CSP-specific costs --
    demand_power:
        e: 0

# Capital depreciation
depreciation:
    default:
        interest: 0.10  # Interest rate [dimensionless]
        plant_life: 25  # Lifetime of a plant [years]
    csp:
        interest: 0.15
