#
# RUN SETTINGS
#

input:
    path:  'Input-Calliope/NA-1hr-full'
    demand: 'D_EU.csv'
    D_max: 80000  # Set to: P_max * len(subset_i) * 0.8

output:
    save: false
    path: 'Output'

#subset_x: [33, 75, 34, 23, 85, 86, 16, 98, 57, 36]  # Leave empty to disable subsetting
subset_x: [33, 75, 34]  # Leave empty to disable subsetting
subset_t: ['2005-01-01', '2005-03-31']

#
# MODEL SETTINGS OVERRIDE
#

override:
#    P_max: 100000
#    sf_max: 7950000
#    E_time: 30
#    scale_sf: 32

#
# SOLVER AND LOGGING
#
# These will usually be set/overridden in parallel_settings.yaml
#

debug:
    keepfiles: false
    symbolic_solver_labels: false

#solver_options:
#    threads: 1
#    lpmethod: 4  # Use barrier method
