#
# RUN SETTINGS
#

input:
    path:  'Input-Calliope/NA-1hr-full'
    demand: 'D_EU.csv'
    D_max: 80000  # Set to: P_max * len(subset_i) * 0.8

output:
    save: false
    path: 'Output'

#
# NODES
#

nodes:
    a:
        level: 1
        within:
        techs: ['ccgt']  # TODO add 'demand' when removing hardcoded 'D'
    0--99:
        level: 0
        within: a
        techs: ['csp']

#
# SUBSETTING
#

subset_y: ['csp', 'ccgt']
subset_x: ['a', '33', '75', '34']  # Leave empty to disable subsetting
subset_t: ['2005-01-01', '2005-03-31']

#
# MODEL SETTINGS OVERRIDE
#

override:
    # constraints:
    #     default:
    #         r_eff: 0.9

#
# SOLVER AND LOGGING
#
# These will usually be set/overridden in parallel_settings.yaml
#

debug:
    keepfiles: false
    symbolic_solver_labels: false

#solver_options:
#    threads: 1
#    lpmethod: 4  # Use barrier method
