#
# RUN SETTINGS
#

input:
    path:  'Input-Calliope/NA-1hr-full'

output:
    save: false
    path: 'Output'

#
# NODES
#

# ONLY the following constraints can be overriden on a per-node and per-tech basis (for now). Attempting to override any others will cause errors or simply be ignored:
# * x_map
# * constraints: r, r_eff, e_eff, r_scale_to_peak, s_cap_max, r_cap_max, r_area_max, e_cap_max

# x_map allows defining which columns in the underlying data file are to be mapped to the node indices defined here.

nodes:
    r1:
        level: 1
        within:
        techs: ['demand']
        override:
            demand:
                x_map: 'a: r1'
                constraints:
                    r: file=demand-eu_r.csv
                    r_scale_to_peak: -60000

    p:
        level: 0
        within: r1
        techs: ['ccgt']
        override:
            ccgt:
                constraints:
                    e_cap_max: 20000
    33,75:
        level: 0
        within: r1
        techs: ['csp']
    34:
        level: 0
        within: r1
        techs: ['csp']
        override:
            csp:
                constraints:
                    e_cap_max: 40000

#
# SUBSETTING
#
# Leave any of these empty to disable subsetting

subset_y: []
subset_x: []
subset_t: ['2005-01-01', '2005-01-31']

#
# MODEL SETTINGS OVERRIDE
#

override:
    techs:
        csp:
            constraints:
                r_scale: 0.001  # Wh in DNI input data --> kWh for model

#
# SOLVER AND LOGGING
#
# These will usually be set/overridden in parallel_settings.yaml
#

debug:
    keepfiles: false
    symbolic_solver_labels: false

#solver_options:
#    threads: 1
#    lpmethod: 4  # Use barrier method
