#
# RUN SETTINGS
#

input:
    path:  'Input-Calliope/NA-1hr-full'

output:
    save: false
    path: 'Output'

#
# NODES
#

nodes:
    a:
        level: 1
        within:
        techs: ['ccgt', 'demand']
    33,75,34:
        level: 0
        within: a
        techs: ['csp']

#
# SUBSETTING
#
# Leave any of these empty to disable subsetting

subset_y: []
subset_x: []
subset_t: ['2005-01-01', '2005-01-31']

#
# MODEL SETTINGS OVERRIDE
#

override:
    constraints:
        csp:
            r_scale: 0.001  # Convert from Wh in DNI input data to kWh for model
        demand:
            r_scale_to_peak: -60000  # Scale demand such that its maximum is as defined here

#
# SOLVER AND LOGGING
#
# These will usually be set/overridden in parallel_settings.yaml
#

debug:
    keepfiles: false
    symbolic_solver_labels: false

#solver_options:
#    threads: 1
#    lpmethod: 4  # Use barrier method
