#
# RUN SETTINGS
#

input:
    path:  'Input-Calliope/NA-1hr-full'

output:
    save: false
    path: 'Output'

#
# NODES
#

# ONLY the following constraints can be overriden on a per-node basis (for now):
# s_cap_max, r_cap_max, r_area_max, e_cap_max

nodes:
    a:
        level: 1
        within:
        techs: ['ccgt', 'demand-eu']
        override:
            ccgt:
                constraints:
                    e_cap_max: 20000
    33,75:
        level: 0
        within: a
        techs: ['csp']
    34:
        level: 0
        within: a
        techs: ['csp']
        override:
            csp:
                constraints:
                    e_cap_max: 40000

#
# SUBSETTING
#
# Leave any of these empty to disable subsetting

subset_y: []
subset_x: []
subset_t: ['2005-01-01', '2005-01-31']

#
# MODEL SETTINGS OVERRIDE
#

override:
    techs:
        demand:
            constraints:
                r_scale_to_peak: -60000  # Scale demand such that its maximum is as defined here
        demand-eu:
            parent: demand
        demand-ca:
            parent: demand
        csp:
            constraints:
                r_scale: 0.001  # Convert from Wh in DNI input data to kWh for model

#
# SOLVER AND LOGGING
#
# These will usually be set/overridden in parallel_settings.yaml
#

debug:
    keepfiles: false
    symbolic_solver_labels: false

#solver_options:
#    threads: 1
#    lpmethod: 4  # Use barrier method
